Loading CUDA/11.1.1-GCC-10.2.0
  Loading requirement: GCCcore/10.2.0 zlib/1.2.11-GCCcore-10.2.0
    binutils/2.35-GCCcore-10.2.0 GCC/10.2.0 CUDAcore/11.1.1
/opt/conda/lib/python3.7/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
Traceback (most recent call last):
  File "mmdetection/custom_inf/folder_inf.py", line 191, in <module>
    main()
  File "mmdetection/custom_inf/folder_inf.py", line 181, in main
    inferencer(inputs=image_path, **call_args)
  File "/mmdetection/mmdet/apis/det_inferencer.py", line 402, in __call__
    if self.show_progress else inputs):
  File "/opt/conda/lib/python3.7/site-packages/rich/progress.py", line 169, in track
    sequence, total=total, description=description, update_period=update_period
  File "/opt/conda/lib/python3.7/site-packages/rich/progress.py", line 1209, in track
    for value in sequence:
  File "/mmdetection/mmdet/apis/det_inferencer.py", line 261, in preprocess
    yield from map(self.collate_fn, chunked_data)
  File "/mmdetection/mmdet/apis/det_inferencer.py", line 288, in _get_chunk_data
    chunk_data.append((inputs_, self.pipeline(inputs_)))
  File "/opt/conda/lib/python3.7/site-packages/mmengine/dataset/base_dataset.py", line 60, in __call__
    data = t(data)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/mmdetection/mmdet/datasets/transforms/loading.py", line 926, in transform
    return self.from_file(inputs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/transforms/loading.py", line 112, in transform
    results['img_shape'] = img.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
